version: "3.5"
services:

  satis:
    image: god:satis
    container_name: satis
    hostname: satis
    volumes:
      - ${HOME}/.ssh/id_rsa:/var/tmp/id
      - ${HOME}/.ssh/config:/var/tmp/sshconf
      - satisconfig:/var/www/.composer
      - ${HOME}/.composer:/composer
      - satisweb:/satisfy/web
    environment:
      PRIVATE_REPO_DOMAIN_LIST: bitbucket.org gitlab.com github.com
      CRONTAB_FREQUENCY: "*/10 * * * *"
    labels:
      - traefik.enable=true
      - traefik.http.routers.satis.tls=true
      - traefik.http.routers.satis.rule=Host(`satis.${WARDEN_SERVICE_DOMAIN:-warden.test}`)
      - traefik.http.services.satis.loadbalancer.server.port=80
    restart: ${WARDEN_RESTART_POLICY:-always}

volumes:
  satisconfig:
  satisweb: