version: "3.5"
services:
  mongo:
    hostname: "${WARDEN_ENV_NAME}-mongo"
    container_name: "${WARDEN_ENV_NAME}-mongo"
    image: mongo:${MONGO_VERSION:-6.0}
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
