version: "3.5"
services:
  mongo-express:
    hostname: "${WARDEN_ENV_NAME}-mongo-express"
    container_name: "${WARDEN_ENV_NAME}-mongo-express"
    image: mongo-express:latest
    environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
        ME_CONFIG_MONGODB_ADMINPASSWORD: mongo
        ME_CONFIG_MONGODB_URL: "mongodb://mongo:mongo@${WARDEN_ENV_NAME}-mongo:27017/"
    depends_on:
      - mongo
    labels:
      - traefik.enable=true
      - traefik.http.routers.${WARDEN_ENV_NAME}-mongo-express.tls=true
      - traefik.http.routers.${WARDEN_ENV_NAME}-mongo-express.rule=Host(`mongo-express.${TRAEFIK_DOMAIN}`)
      - traefik.http.services.${WARDEN_ENV_NAME}-mongo-express.loadbalancer.server.port=8081
      - traefik.docker.network=${WARDEN_ENV_NAME}_default