version: "3.5"
services:
  ngrok:
    image: ngrok/ngrok
    hostname: "${WARDEN_ENV_NAME}-ngrok"
    command: "http ${WARDEN_ENV_NAME}_nginx_1:80"
    environment:
      - NGROK_AUTHTOKEN=soeJP8P6k3EKLoNCZXYG_6WvSe2q6SxJsijbUnznoK
    depends_on:
      - nginx
    links:
      - nginx
    labels:
      - traefik.enable=true
      - traefik.http.routers.${WARDEN_ENV_NAME}-ngrok.tls=true
      - traefik.http.routers.${WARDEN_ENV_NAME}-ngrok.rule=Host(`ngrok.${TRAEFIK_DOMAIN}`)
      - traefik.http.services.${WARDEN_ENV_NAME}-ngrok.loadbalancer.server.port=4040
      - traefik.docker.network=${WARDEN_ENV_NAME}_default

